<h1 align="left">ğŸ‘‹ Hi, I'm Shabiha Kalam Ansari</h1>

###

<br clear="both">

<div align="center">
  <img height="190" src="https://media.licdn.com/dms/image/v2/D4D16AQFABTJEw5o-8w/profile-displaybackgroundimage-shrink_350_1400/B4DZtqfi4qGUAY-/0/1767018216352?e=1768435200&v=beta&t=Z2fOFiXS48S4kLHi9etzAWFPbpv9wX_GpLqqGTjIkPU"  />
</div>

###

<p align="left">Computer Science & Engineering | Web Development Learner | <br>HTML â€¢ CSS â€¢ JavaScript<br><br>Aspiring Web Developer  | Aspiring Software Developer | Programming</p>

###

<h2 align="left">About me</h2>

###

<p align="left">ğŸ“ Diploma in Computer Science & Engineering from Al Kabir Polytechnic JHARKHAND , JAMSHEDPUR;<br>ğŸ“š Currently pursuing B.Tech in CSE WEST BENGAL , KOLKATA;<br>ğŸ’¡ Curious learner with a growth mindset<br>ğŸ” Interested in Web Development and Programming<br>ğŸ’ª Hardworking, consistent, and never-give-up attitude</p>

###

<h2 align="left">Tech Stack</h2>

###

<div align="left">
  <img src="https://skillicons.dev/icons?i=c" height="40" alt="c logo"  />
  <img width="12" />
  <img src="https://skillicons.dev/icons?i=cpp" height="40" alt="cplusplus logo"  />
  <img width="12" />
  <img src="https://skillicons.dev/icons?i=java" height="40" alt="java logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg" height="40" alt="html5 logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" height="40" alt="css logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" height="40" alt="javascript logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/php/php-original.svg" height="40" alt="php logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg" height="40" alt="vscode logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" height="40" alt="react logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/devicon/devicon-original.svg" height="40" alt="devicon logo"  />
  <img width="12" />
  <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg" height="40" alt="mysql logo"  />
</div>

###

<div align="left">
  <a href="www.linkedin.com/in/shabihakalamansari" target="_blank">
    <img src="https://raw.githubusercontent.com/maurodesouza/profile-readme-generator/master/src/assets/icons/social/linkedin/default.svg" width="52" height="40" alt="linkedin logo"  />
  </a>
</div>

###

<img src="https://raw.githubusercontent.com/SHABIHA77/SHABIHA77/output/snake.svg" alt="Snake animation" />

###

<div>
  <img style="100%" src="https://capsule-render.vercel.app/api?type=waving&height=100&section=header&reversal=false&fontSize=70&fontColor=FFFFFF&fontAlign=50&fontAlignY=50&stroke=-&descSize=20&descAlign=50&descAlignY=50&theme=cobalt"  />
</div>

###
